[build]
  functions = "netlify/functions"
  command = "pip install -r requirements.txt"
  publish = "." # Direktori root proyek Anda

[functions]
  included_files = ["app.py", "templates/**"] # Sertakan file aplikasi dan template

[environment]
  MONGO_URI = "mongodb+srv://ekaaic09:ekasaputra09@cluster0.x8qgbso.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  DATABASE_NAME = "inventory_db"
  SECRET_KEY = "your_super_secret_key_here_at_least_32_chars_long_and_random"
  ADMIN_USERNAME = "admin"
  ADMIN_PASSWORD = "admin_password123"