[build]
  functions = "netlify/functions"
  command = "pip install -r requirements.txt"
  publish = "."

[functions]
  included_files = ["app.py", "templates/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/handler/:splat"
  status = 200